# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /fs03/share/users/pe.cochet/home/Documents/4IRC/ImplementationReseau/Projet/IRCChat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /fs03/share/users/pe.cochet/home/Documents/4IRC/ImplementationReseau/Projet/IRCChat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/pe.cochet/home/Documents/4IRC/ImplementationReseau/Projet/IRCChat/CMakeFiles /fs03/share/users/pe.cochet/home/Documents/4IRC/ImplementationReseau/Projet/IRCChat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /fs03/share/users/pe.cochet/home/Documents/4IRC/ImplementationReseau/Projet/IRCChat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClientIRCChat

# Build rule for target.
ClientIRCChat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClientIRCChat
.PHONY : ClientIRCChat

# fast build rule for target.
ClientIRCChat/fast:
	$(MAKE) -f CMakeFiles/ClientIRCChat.dir/build.make CMakeFiles/ClientIRCChat.dir/build
.PHONY : ClientIRCChat/fast

#=============================================================================
# Target rules for targets named ServeurIRCChat

# Build rule for target.
ServeurIRCChat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ServeurIRCChat
.PHONY : ServeurIRCChat

# fast build rule for target.
ServeurIRCChat/fast:
	$(MAKE) -f CMakeFiles/ServeurIRCChat.dir/build.make CMakeFiles/ServeurIRCChat.dir/build
.PHONY : ServeurIRCChat/fast

client.o: client.c.o
.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) -f CMakeFiles/ClientIRCChat.dir/build.make CMakeFiles/ClientIRCChat.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) -f CMakeFiles/ClientIRCChat.dir/build.make CMakeFiles/ClientIRCChat.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) -f CMakeFiles/ClientIRCChat.dir/build.make CMakeFiles/ClientIRCChat.dir/client.c.s
.PHONY : client.c.s

serveur-udp.o: serveur-udp.c.o
.PHONY : serveur-udp.o

# target to build an object file
serveur-udp.c.o:
	$(MAKE) -f CMakeFiles/ServeurIRCChat.dir/build.make CMakeFiles/ServeurIRCChat.dir/serveur-udp.c.o
.PHONY : serveur-udp.c.o

serveur-udp.i: serveur-udp.c.i
.PHONY : serveur-udp.i

# target to preprocess a source file
serveur-udp.c.i:
	$(MAKE) -f CMakeFiles/ServeurIRCChat.dir/build.make CMakeFiles/ServeurIRCChat.dir/serveur-udp.c.i
.PHONY : serveur-udp.c.i

serveur-udp.s: serveur-udp.c.s
.PHONY : serveur-udp.s

# target to generate assembly for a file
serveur-udp.c.s:
	$(MAKE) -f CMakeFiles/ServeurIRCChat.dir/build.make CMakeFiles/ServeurIRCChat.dir/serveur-udp.c.s
.PHONY : serveur-udp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ClientIRCChat"
	@echo "... ServeurIRCChat"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... serveur-udp.o"
	@echo "... serveur-udp.i"
	@echo "... serveur-udp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

